name: Cypress test runners FAIL

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-test-fail:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Try to fail
        run: exit 1
      - name: Print message if we don't fail
        run: echo Should not get here